### ISSUE TITLE
 How to convert JsonValue to String

### ISSUE THREAD

**Issue by DenineLu** [simdjson/simdjson-java#55] opened 2024-06-24 04:01 UTC
For DOM parser, how to convert JsonValue to byte array or string? For example:
```java
byte[] json = toUtf8("{\"a\": {\"b\": \"c\"}}");
JsonValue jsonValue = parser.parse(json, json.length);
JsonValue res = jsonValue.get("a");
```
I want to get the string `{"b": "c"}`. Thank you in advance for your help with this question.

**Comment by piotrrzysko** [comment] 2024-10-20 07:58
This looks like a duplicate of https://github.com/simdjson/simdjson-java/issues/39. Feel free to reopen it if my understanding is incorrect.

**Closed by piotrrzysko** 2024-10-20 07:58 UTC
